name: Echo Environment Variables

on: [push, pull_request]

jobs:
  echo_env_vars:
    runs-on: ubuntu-latest
    steps:
      - name: Echo Variables
        run: |
          echo "Source Branch   --> $GITHUB_HEAD_REF"
          echo "Target Branch   --> $GITHUB_BASE_REF"
          echo "Pull Request Id --> $GITHUB_REF"
